import java.util.ArrayList;
import java.util.List;
import java.util.function.DoubleConsumer;
import java.util.function.IntUnaryOperator;

public class MyMain {
    // READ THE README IF CONFUSED

    /**
     * Write an IntUnaryOperator (a functional interface representing an operation on a single int that returns an int)
     * which gives the value of that integer + 1.
     * @return the IntUnaryOperator which returns the value of the argument increased by one.
     */
    public static IntUnaryOperator increment () {
        return new IntUnaryOperator() {
            @Override // Ignore this line, it's just helping the compiler understand the code and is autogenerated by IntelliJ
            public int applyAsInt(int operand) {
                return 0;
            }
        };
    }

    /*
     * Functional interfaces look complicated, but they're actually really simple! A class implementing a functional interface
     * simply has one method: the function being represented by the object. For an example, see problem 1 in `MyMain.java`.
     * Because they're so simple, there's a special notation that allows you to create them very easily (but you can still use
     * the complicated version). This is called "lambda notation" or simply a lambda, and you can see an example of it in
     * problem 2 in `MyMain.java`.
     */

    /**
     * Very similar to the above problem, but this one is set up to use a lambda. Notice how all the key information
     * from above is repeated.
     * @return the IntUnaryOperator which returns the value of the argument decreased by one.
     */
    public static IntUnaryOperator decrement () {
        return (int operand) -> {
            /*YOUR CODE HERE*/
        };
    }

    /**
     * Now, you're on your own. Return a DoubleConsumer (a function which accepts a double and doesn't return anything)
     * which adds the double to a given list.
     * @param list A list which the DoubleConsumer adds to.
     * @return The DoubleConsumer which adds its arguments to the List
     */
    public static DoubleConsumer addToList (List<Double> list) {
        return null;
    }

}
